# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_licensed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_licensed', models.BooleanField(default=False)),
            ],
        ),
    ]
